# -*- coding: utf-8 -*-
__author__ = 'akiokio'

simple_order = {'adjustment_negative': None,
         'adjustment_positive': None,
         'affiliateplus_discount': None,
         'applied_rule_ids': '1',
         'base_adjustment_negative': None,
         'base_adjustment_positive': None,
         'base_affiliateplus_discount': None,
         'base_currency_code': 'BRL',
         'base_discount_amount': '0.0000',
         'base_discount_canceled': None,
         'base_discount_invoiced': '0.0000',
         'base_discount_refunded': None,
         'base_grand_total': '203.8900',
         'base_hidden_tax_amount': '0.0000',
         'base_hidden_tax_invoiced': '0.0000',
         'base_hidden_tax_refunded': None,
         'base_shipping_amount': '0.0000',
         'base_shipping_canceled': None,
         'base_shipping_discount_amount': '0.0000',
         'base_shipping_hidden_tax_amnt': '0.0000',
         'base_shipping_hidden_tax_amount': '0.0000',
         'base_shipping_incl_tax': '0.0000',
         'base_shipping_invoiced': '0.0000',
         'base_shipping_refunded': None,
         'base_shipping_tax_amount': '0.0000',
         'base_shipping_tax_refunded': None,
         'base_subtotal': '203.8900',
         'base_subtotal_canceled': None,
         'base_subtotal_incl_tax': '203.8900',
         'base_subtotal_invoiced': '203.8900',
         'base_subtotal_refunded': None,
         'base_tax_amount': '0.0000',
         'base_tax_canceled': None,
         'base_tax_invoiced': '0.0000',
         'base_tax_refunded': None,
         'base_to_global_rate': '1.0000',
         'base_to_order_rate': '1.0000',
         'base_total_canceled': None,
         'base_total_due': None,
         'base_total_invoiced': '203.8900',
         'base_total_invoiced_cost': '0.0000',
         'base_total_offline_refunded': None,
         'base_total_online_refunded': None,
         'base_total_paid': '203.8900',
         'base_total_qty_ordered': None,
         'base_total_refunded': None,
         'billing_address': {'address_id': '22579',
                             'address_type': 'billing',
                             'celular': None,
                             'city': u'Xanxer\xea',
                             'company': None,
                             'country_id': 'BR',
                             'cpfcnpj': None,
                             'customer_address_id': '15938',
                             'customer_id': None,
                             'email': 'bian_ros@hotmail.com',
                             'fax': None,
                             'firstname': 'Matheus',
                             'ie': None,
                             'lastname': 'Brusamarello',
                             'middlename': None,
                             'parent_id': '11290',
                             'postcode': '89820-000',
                             'prefix': None,
                             'quote_address_id': None,
                             'region': 'Santa Catarina',
                             'region_id': '507',
                             'rg': None,
                             'street': u'R. Independ\xeancia\n1034\n402\nLa Salle',
                             'suffix': None,
                             'telephone': '(49)9989-7917',
                             'tipopessoa': None,
                             'vat_id': None,
                             'vat_is_valid': None,
                             'vat_request_date': None,
                             'vat_request_id': None,
                             'vat_request_success': None},
         'billing_address_id': '22579',
         'can_ship_partially': None,
         'can_ship_partially_item': None,
         'coupon_code': None,
         'coupon_rule_name': None,
         'created_at': '2013-06-28 17:08:20',
         'customer_dob': None,
         'customer_email': 'bian_ros@hotmail.com',
         'customer_firstname': 'Matheus',
         'customer_gender': None,
         'customer_group_id': '1',
         'customer_id': '14201',
         'customer_is_guest': '0',
         'customer_lastname': 'Brusamarello',
         'customer_middlename': None,
         'customer_note': None,
         'customer_note_notify': '1',
         'customer_prefix': None,
         'customer_suffix': None,
         'customer_taxvat': '077.989.189-90',
         'discount_amount': '0.0000',
         'discount_canceled': None,
         'discount_description': None,
         'discount_invoiced': '0.0000',
         'discount_refunded': None,
         'edit_increment': None,
         'email_sent': '1',
         'ext_customer_id': None,
         'ext_order_id': None,
         'forced_do_shipment_with_invoice': None,
         'forced_shipment_with_invoice': None,
         'gift_message_id': None,
         'global_currency_code': 'BRL',
         'grand_total': '203.8900',
         'hidden_tax_amount': '0.0000',
         'hidden_tax_invoiced': '0.0000',
         'hidden_tax_refunded': None,
         'hold_before_state': None,
         'hold_before_status': None,
         'increment_id': '100011294',
         'is_virtual': '0',
         'items': [{'additional_data': None,
                    'affiliateplus_amount': None,
                    'affiliateplus_commission': '0.0000',
                    'amount_refunded': '0.0000',
                    'applied_rule_ids': '1',
                    'base_affiliateplus_amount': None,
                    'base_amount_refunded': '0.0000',
                    'base_cost': None,
                    'base_discount_amount': '0.0000',
                    'base_discount_invoiced': '0.0000',
                    'base_discount_refunded': None,
                    'base_hidden_tax_amount': None,
                    'base_hidden_tax_invoiced': '0.0000',
                    'base_hidden_tax_refunded': None,
                    'base_original_price': '168.9900',
                    'base_price': '168.9900',
                    'base_price_incl_tax': '168.9900',
                    'base_row_invoiced': '168.9900',
                    'base_row_total': '168.9900',
                    'base_row_total_incl_tax': '168.9900',
                    'base_tax_amount': '0.0000',
                    'base_tax_before_discount': None,
                    'base_tax_invoiced': '0.0000',
                    'base_tax_refunded': None,
                    'base_weee_tax_applied_amount': '0.0000',
                    'base_weee_tax_applied_row_amnt': '0.0000',
                    'base_weee_tax_applied_row_amount': '0.0000',
                    'base_weee_tax_disposition': '0.0000',
                    'base_weee_tax_row_disposition': '0.0000',
                    'created_at': '2013-06-28 17:08:20',
                    'description': None,
                    'discount_amount': '0.0000',
                    'discount_invoiced': '0.0000',
                    'discount_percent': '0.0000',
                    'discount_refunded': None,
                    'ext_order_item_id': None,
                    'free_shipping': '0',
                    'gift_message_available': None,
                    'gift_message_id': None,
                    'has_children': True,
                    'hidden_tax_amount': None,
                    'hidden_tax_canceled': None,
                    'hidden_tax_invoiced': '0.0000',
                    'hidden_tax_refunded': None,
                    'is_nominal': '0',
                    'is_qty_decimal': '0',
                    'is_virtual': '0',
                    'item_id': '30307',
                    'locked_do_invoice': None,
                    'locked_do_ship': None,
                    'name': '100% Whey Protein Gold Standard - 2lbs - Optimum ',
                    'no_discount': '0',
                    'order_id': '11290',
                    'original_price': '168.9900',
                    'parent_item_id': None,
                    'price': '168.9900',
                    'price_incl_tax': '168.9900',
                    'product_id': '1303',
                    'product_options': 'a:6:{s:15:"info_buyRequest";a:5:{s:4:"uenc";s:116:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici8xMDAtd2hleS1wcm90ZWluLWdvbGQtc3RhbmRhcmQtMmxicy1vcHRpbXVtLmh0bWw_X19fU0lEPVU,";s:7:"product";s:4:"1303";s:15:"related_product";s:0:"";s:15:"super_attribute";a:1:{i:135;s:3:"113";}s:3:"qty";s:1:"1";}s:15:"attributes_info";a:1:{i:0;a:2:{s:5:"label";s:5:"Sabor";s:5:"value";s:17:"Vanilla Ice Cream";}}s:11:"simple_name";s:68:"100% Whey Protein Gold Standard - 2lbs - Optimum - Vanilla Ice Cream";s:10:"simple_sku";s:4:"2290";s:20:"product_calculations";i:1;s:13:"shipment_type";i:0;}',
                    'product_type': 'configurable',
                    'qty_backordered': None,
                    'qty_canceled': '0.0000',
                    'qty_invoiced': '1.0000',
                    'qty_ordered': '1.0000',
                    'qty_refunded': '0.0000',
                    'qty_shipped': '0.0000',
                    'quote_item_id': '96494',
                    'row_invoiced': '168.9900',
                    'row_total': '168.9900',
                    'row_total_incl_tax': '168.9900',
                    'row_weight': '0.0000',
                    'sku': '2290',
                    'store_id': '1',
                    'tax_amount': '0.0000',
                    'tax_before_discount': None,
                    'tax_canceled': None,
                    'tax_invoiced': '0.0000',
                    'tax_percent': '0.0000',
                    'tax_refunded': None,
                    'updated_at': '2013-06-28 17:08:27',
                    'weee_tax_applied': 'a:0:{}',
                    'weee_tax_applied_amount': '0.0000',
                    'weee_tax_applied_row_amount': '0.0000',
                    'weee_tax_disposition': '0.0000',
                    'weee_tax_row_disposition': '0.0000',
                    'weight': '1.1000'},
                   {'additional_data': None,
                    'affiliateplus_amount': None,
                    'affiliateplus_commission': '0.0000',
                    'amount_refunded': '0.0000',
                    'applied_rule_ids': '1',
                    'base_affiliateplus_amount': None,
                    'base_amount_refunded': '0.0000',
                    'base_cost': None,
                    'base_discount_amount': '0.0000',
                    'base_discount_invoiced': '0.0000',
                    'base_discount_refunded': None,
                    'base_hidden_tax_amount': None,
                    'base_hidden_tax_invoiced': '0.0000',
                    'base_hidden_tax_refunded': None,
                    'base_original_price': None,
                    'base_price': '0.0000',
                    'base_price_incl_tax': None,
                    'base_row_invoiced': '0.0000',
                    'base_row_total': '0.0000',
                    'base_row_total_incl_tax': None,
                    'base_tax_amount': '0.0000',
                    'base_tax_before_discount': None,
                    'base_tax_invoiced': '0.0000',
                    'base_tax_refunded': None,
                    'base_weee_tax_applied_amount': '0.0000',
                    'base_weee_tax_applied_row_amnt': None,
                    'base_weee_tax_applied_row_amount': None,
                    'base_weee_tax_disposition': '0.0000',
                    'base_weee_tax_row_disposition': '0.0000',
                    'created_at': '2013-06-28 17:08:20',
                    'description': None,
                    'discount_amount': '0.0000',
                    'discount_invoiced': '0.0000',
                    'discount_percent': '0.0000',
                    'discount_refunded': None,
                    'ext_order_item_id': None,
                    'free_shipping': '0',
                    'gift_message_available': None,
                    'gift_message_id': None,
                    'hidden_tax_amount': None,
                    'hidden_tax_canceled': None,
                    'hidden_tax_invoiced': '0.0000',
                    'hidden_tax_refunded': None,
                    'is_nominal': '0',
                    'is_qty_decimal': '0',
                    'is_virtual': '0',
                    'item_id': '30308',
                    'locked_do_invoice': None,
                    'locked_do_ship': None,
                    'name': '100% Whey Protein Gold Standard - 2lbs - Optimum - Vanilla Ice Cream',
                    'no_discount': '0',
                    'order_id': '11290',
                    'original_price': '0.0000',
                    'parent_item_id': '30307',
                    'price': '0.0000',
                    'price_incl_tax': None,
                    'product_id': '1309',
                    'product_options': 'a:1:{s:15:"info_buyRequest";a:7:{s:4:"uenc";s:116:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici8xMDAtd2hleS1wcm90ZWluLWdvbGQtc3RhbmRhcmQtMmxicy1vcHRpbXVtLmh0bWw_X19fU0lEPVU,";s:7:"product";s:4:"1303";s:15:"related_product";s:0:"";s:15:"super_attribute";a:1:{i:135;s:3:"113";}s:3:"qty";s:1:"1";s:12:"freegift_key";s:32:"269d837afada308dd4aeab28ca2d57e4";s:13:"apllied_rules";s:32:"a:2:{i:0;s:2:"12";i:1;s:2:"29";}";}}',
                    'product_type': 'simple',
                    'qty_backordered': None,
                    'qty_canceled': '0.0000',
                    'qty_invoiced': '1.0000',
                    'qty_ordered': '1.0000',
                    'qty_refunded': '0.0000',
                    'qty_shipped': '0.0000',
                    'quote_item_id': '96495',
                    'row_invoiced': '0.0000',
                    'row_total': '0.0000',
                    'row_total_incl_tax': None,
                    'row_weight': '0.0000',
                    'sku': '2290',
                    'store_id': '1',
                    'tax_amount': '0.0000',
                    'tax_before_discount': None,
                    'tax_canceled': None,
                    'tax_invoiced': '0.0000',
                    'tax_percent': '0.0000',
                    'tax_refunded': None,
                    'updated_at': '2013-06-28 17:08:27',
                    'weee_tax_applied': 'a:0:{}',
                    'weee_tax_applied_amount': '0.0000',
                    'weee_tax_applied_row_amount': '0.0000',
                    'weee_tax_disposition': '0.0000',
                    'weee_tax_row_disposition': '0.0000',
                    'weight': '1.1000'},
                   {'additional_data': None,
                    'affiliateplus_amount': None,
                    'affiliateplus_commission': '0.0000',
                    'amount_refunded': '0.0000',
                    'applied_rule_ids': '1',
                    'base_affiliateplus_amount': None,
                    'base_amount_refunded': '0.0000',
                    'base_cost': None,
                    'base_discount_amount': '0.0000',
                    'base_discount_invoiced': '0.0000',
                    'base_discount_refunded': None,
                    'base_hidden_tax_amount': None,
                    'base_hidden_tax_invoiced': '0.0000',
                    'base_hidden_tax_refunded': None,
                    'base_original_price': '0.0000',
                    'base_price': '0.0000',
                    'base_price_incl_tax': '0.0000',
                    'base_row_invoiced': '0.0000',
                    'base_row_total': '0.0000',
                    'base_row_total_incl_tax': '0.0000',
                    'base_tax_amount': '0.0000',
                    'base_tax_before_discount': None,
                    'base_tax_invoiced': '0.0000',
                    'base_tax_refunded': None,
                    'base_weee_tax_applied_amount': '0.0000',
                    'base_weee_tax_applied_row_amnt': '0.0000',
                    'base_weee_tax_applied_row_amount': '0.0000',
                    'base_weee_tax_disposition': '0.0000',
                    'base_weee_tax_row_disposition': '0.0000',
                    'created_at': '2013-06-28 17:08:20',
                    'description': None,
                    'discount_amount': '0.0000',
                    'discount_invoiced': '0.0000',
                    'discount_percent': '0.0000',
                    'discount_refunded': None,
                    'ext_order_item_id': None,
                    'free_shipping': '0',
                    'gift_message_available': None,
                    'gift_message_id': None,
                    'hidden_tax_amount': None,
                    'hidden_tax_canceled': None,
                    'hidden_tax_invoiced': '0.0000',
                    'hidden_tax_refunded': None,
                    'is_nominal': '0',
                    'is_qty_decimal': '0',
                    'is_virtual': '0',
                    'item_id': '30309',
                    'locked_do_invoice': None,
                    'locked_do_ship': None,
                    'name': u'Luva Protetora para Muscula\xe7\xe3o - CentralFit',
                    'no_discount': '0',
                    'order_id': '11290',
                    'original_price': '0.0000',
                    'parent_item_id': None,
                    'price': '0.0000',
                    'price_incl_tax': '0.0000',
                    'product_id': '2108',
                    'product_options': u'a:1:{s:15:"info_buyRequest";a:6:{s:4:"uenc";s:116:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici8xMDAtd2hleS1wcm90ZWluLWdvbGQtc3RhbmRhcmQtMmxicy1vcHRpbXVtLmh0bWw_X19fU0lEPVU,";s:7:"product";s:4:"2108";s:3:"qty";d:1;s:17:"free_catalog_gift";i:1;s:19:"freegift_parent_key";s:32:"269d837afada308dd4aeab28ca2d57e4";s:6:"option";s:59:"a:2:{s:5:"label";s:14:"BRINDE GR\xc1TIS";s:5:"value";s:0:"";}";}}',
                    'product_type': 'simple',
                    'qty_backordered': None,
                    'qty_canceled': '0.0000',
                    'qty_invoiced': '1.0000',
                    'qty_ordered': '1.0000',
                    'qty_refunded': '0.0000',
                    'qty_shipped': '0.0000',
                    'quote_item_id': '96496',
                    'row_invoiced': '0.0000',
                    'row_total': '0.0000',
                    'row_total_incl_tax': '0.0000',
                    'row_weight': '0.0000',
                    'sku': '3059',
                    'store_id': '1',
                    'tax_amount': '0.0000',
                    'tax_before_discount': None,
                    'tax_canceled': None,
                    'tax_invoiced': '0.0000',
                    'tax_percent': '0.0000',
                    'tax_refunded': None,
                    'updated_at': '2013-06-28 17:08:27',
                    'weee_tax_applied': 'a:0:{}',
                    'weee_tax_applied_amount': '0.0000',
                    'weee_tax_applied_row_amount': '0.0000',
                    'weee_tax_disposition': '0.0000',
                    'weee_tax_row_disposition': '0.0000',
                    'weight': '0.0500'},
                   {'additional_data': None,
                    'affiliateplus_amount': None,
                    'affiliateplus_commission': '0.0000',
                    'amount_refunded': '0.0000',
                    'applied_rule_ids': '1',
                    'base_affiliateplus_amount': None,
                    'base_amount_refunded': '0.0000',
                    'base_cost': None,
                    'base_discount_amount': '0.0000',
                    'base_discount_invoiced': '0.0000',
                    'base_discount_refunded': None,
                    'base_hidden_tax_amount': None,
                    'base_hidden_tax_invoiced': '0.0000',
                    'base_hidden_tax_refunded': None,
                    'base_original_price': '0.0000',
                    'base_price': '0.0000',
                    'base_price_incl_tax': '0.0000',
                    'base_row_invoiced': '0.0000',
                    'base_row_total': '0.0000',
                    'base_row_total_incl_tax': '0.0000',
                    'base_tax_amount': '0.0000',
                    'base_tax_before_discount': None,
                    'base_tax_invoiced': '0.0000',
                    'base_tax_refunded': None,
                    'base_weee_tax_applied_amount': '0.0000',
                    'base_weee_tax_applied_row_amnt': '0.0000',
                    'base_weee_tax_applied_row_amount': '0.0000',
                    'base_weee_tax_disposition': '0.0000',
                    'base_weee_tax_row_disposition': '0.0000',
                    'created_at': '2013-06-28 17:08:20',
                    'description': None,
                    'discount_amount': '0.0000',
                    'discount_invoiced': '0.0000',
                    'discount_percent': '0.0000',
                    'discount_refunded': None,
                    'ext_order_item_id': None,
                    'free_shipping': '0',
                    'gift_message_available': None,
                    'gift_message_id': None,
                    'hidden_tax_amount': None,
                    'hidden_tax_canceled': None,
                    'hidden_tax_invoiced': '0.0000',
                    'hidden_tax_refunded': None,
                    'is_nominal': '0',
                    'is_qty_decimal': '0',
                    'is_virtual': '0',
                    'item_id': '30310',
                    'locked_do_invoice': None,
                    'locked_do_ship': None,
                    'name': 'Coqueteleira Shaker - 700ml - NeoNutri',
                    'no_discount': '0',
                    'order_id': '11290',
                    'original_price': '0.0000',
                    'parent_item_id': None,
                    'price': '0.0000',
                    'price_incl_tax': '0.0000',
                    'product_id': '1345',
                    'product_options': u'a:1:{s:15:"info_buyRequest";a:6:{s:4:"uenc";s:116:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici8xMDAtd2hleS1wcm90ZWluLWdvbGQtc3RhbmRhcmQtMmxicy1vcHRpbXVtLmh0bWw_X19fU0lEPVU,";s:7:"product";s:4:"1345";s:3:"qty";d:1;s:17:"free_catalog_gift";i:1;s:19:"freegift_parent_key";s:32:"269d837afada308dd4aeab28ca2d57e4";s:6:"option";s:59:"a:2:{s:5:"label";s:14:"BRINDE GR\xc1TIS";s:5:"value";s:0:"";}";}}',
                    'product_type': 'simple',
                    'qty_backordered': None,
                    'qty_canceled': '0.0000',
                    'qty_invoiced': '1.0000',
                    'qty_ordered': '1.0000',
                    'qty_refunded': '0.0000',
                    'qty_shipped': '0.0000',
                    'quote_item_id': '96497',
                    'row_invoiced': '0.0000',
                    'row_total': '0.0000',
                    'row_total_incl_tax': '0.0000',
                    'row_weight': '0.0000',
                    'sku': '2326',
                    'store_id': '1',
                    'tax_amount': '0.0000',
                    'tax_before_discount': None,
                    'tax_canceled': None,
                    'tax_invoiced': '0.0000',
                    'tax_percent': '0.0000',
                    'tax_refunded': None,
                    'updated_at': '2013-06-28 17:08:27',
                    'weee_tax_applied': 'a:0:{}',
                    'weee_tax_applied_amount': '0.0000',
                    'weee_tax_applied_row_amount': '0.0000',
                    'weee_tax_disposition': '0.0000',
                    'weee_tax_row_disposition': '0.0000',
                    'weight': '0.1500'},
                   {'additional_data': None,
                    'affiliateplus_amount': None,
                    'affiliateplus_commission': '0.0000',
                    'amount_refunded': '0.0000',
                    'applied_rule_ids': '1',
                    'base_affiliateplus_amount': None,
                    'base_amount_refunded': '0.0000',
                    'base_cost': None,
                    'base_discount_amount': '0.0000',
                    'base_discount_invoiced': '0.0000',
                    'base_discount_refunded': None,
                    'base_hidden_tax_amount': None,
                    'base_hidden_tax_invoiced': '0.0000',
                    'base_hidden_tax_refunded': None,
                    'base_original_price': '34.9000',
                    'base_price': '34.9000',
                    'base_price_incl_tax': '34.9000',
                    'base_row_invoiced': '34.9000',
                    'base_row_total': '34.9000',
                    'base_row_total_incl_tax': '34.9000',
                    'base_tax_amount': '0.0000',
                    'base_tax_before_discount': None,
                    'base_tax_invoiced': '0.0000',
                    'base_tax_refunded': None,
                    'base_weee_tax_applied_amount': '0.0000',
                    'base_weee_tax_applied_row_amnt': '0.0000',
                    'base_weee_tax_applied_row_amount': '0.0000',
                    'base_weee_tax_disposition': '0.0000',
                    'base_weee_tax_row_disposition': '0.0000',
                    'created_at': '2013-06-28 17:08:20',
                    'description': None,
                    'discount_amount': '0.0000',
                    'discount_invoiced': '0.0000',
                    'discount_percent': '0.0000',
                    'discount_refunded': None,
                    'ext_order_item_id': None,
                    'free_shipping': '0',
                    'gift_message_available': None,
                    'gift_message_id': None,
                    'has_children': True,
                    'hidden_tax_amount': None,
                    'hidden_tax_canceled': None,
                    'hidden_tax_invoiced': '0.0000',
                    'hidden_tax_refunded': None,
                    'is_nominal': '0',
                    'is_qty_decimal': '0',
                    'is_virtual': '0',
                    'item_id': '30311',
                    'locked_do_invoice': None,
                    'locked_do_ship': None,
                    'name': u'VO2 Slim Protein Bar 12 unidades - Integralm\xe9dica',
                    'no_discount': '0',
                    'order_id': '11290',
                    'original_price': '34.9000',
                    'parent_item_id': None,
                    'price': '34.9000',
                    'price_incl_tax': '34.9000',
                    'product_id': '105',
                    'product_options': u'a:6:{s:15:"info_buyRequest";a:5:{s:4:"uenc";s:184:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9tYXNzYS1lLWVuZXJnaWEvY2F0ZWdvcmlhcy9iYXJyYXMtZGUtcHJvdGVpbmFzL3ZvMi1zbGltLXByb3RlaW4tYmFyLTEyLXVuaWRhZGVzLWludGVncmFsbWVkaWNhLmh0bWw_X19fU0lEPVU,";s:7:"product";s:3:"105";s:15:"related_product";s:0:"";s:15:"super_attribute";a:1:{i:135;s:2:"12";}s:3:"qty";s:1:"1";}s:15:"attributes_info";a:1:{i:0;a:2:{s:5:"label";s:5:"Sabor";s:5:"value";s:37:"Frutas Vermelhas com Chocolate Branco";}}s:11:"simple_name";s:77:"VO2 Slim Protein Bar 12 unidades - Integralm\xe9dica - Frutas Verm/Choc. Branco";s:10:"simple_sku";s:3:"214";s:20:"product_calculations";i:1;s:13:"shipment_type";i:0;}',
                    'product_type': 'configurable',
                    'qty_backordered': None,
                    'qty_canceled': '0.0000',
                    'qty_invoiced': '1.0000',
                    'qty_ordered': '1.0000',
                    'qty_refunded': '0.0000',
                    'qty_shipped': '0.0000',
                    'quote_item_id': '96513',
                    'row_invoiced': '34.9000',
                    'row_total': '34.9000',
                    'row_total_incl_tax': '34.9000',
                    'row_weight': '0.0000',
                    'sku': '214',
                    'store_id': '1',
                    'tax_amount': '0.0000',
                    'tax_before_discount': None,
                    'tax_canceled': None,
                    'tax_invoiced': '0.0000',
                    'tax_percent': '0.0000',
                    'tax_refunded': None,
                    'updated_at': '2013-06-28 17:08:27',
                    'weee_tax_applied': 'a:0:{}',
                    'weee_tax_applied_amount': '0.0000',
                    'weee_tax_applied_row_amount': '0.0000',
                    'weee_tax_disposition': '0.0000',
                    'weee_tax_row_disposition': '0.0000',
                    'weight': '0.5000'},
                   {'additional_data': None,
                    'affiliateplus_amount': None,
                    'affiliateplus_commission': '0.0000',
                    'amount_refunded': '0.0000',
                    'applied_rule_ids': '1',
                    'base_affiliateplus_amount': None,
                    'base_amount_refunded': '0.0000',
                    'base_cost': None,
                    'base_discount_amount': '0.0000',
                    'base_discount_invoiced': '0.0000',
                    'base_discount_refunded': None,
                    'base_hidden_tax_amount': None,
                    'base_hidden_tax_invoiced': '0.0000',
                    'base_hidden_tax_refunded': None,
                    'base_original_price': None,
                    'base_price': '0.0000',
                    'base_price_incl_tax': None,
                    'base_row_invoiced': '0.0000',
                    'base_row_total': '0.0000',
                    'base_row_total_incl_tax': None,
                    'base_tax_amount': '0.0000',
                    'base_tax_before_discount': None,
                    'base_tax_invoiced': '0.0000',
                    'base_tax_refunded': None,
                    'base_weee_tax_applied_amount': '0.0000',
                    'base_weee_tax_applied_row_amnt': None,
                    'base_weee_tax_applied_row_amount': None,
                    'base_weee_tax_disposition': '0.0000',
                    'base_weee_tax_row_disposition': '0.0000',
                    'created_at': '2013-06-28 17:08:20',
                    'description': None,
                    'discount_amount': '0.0000',
                    'discount_invoiced': '0.0000',
                    'discount_percent': '0.0000',
                    'discount_refunded': None,
                    'ext_order_item_id': None,
                    'free_shipping': '0',
                    'gift_message_available': None,
                    'gift_message_id': None,
                    'hidden_tax_amount': None,
                    'hidden_tax_canceled': None,
                    'hidden_tax_invoiced': '0.0000',
                    'hidden_tax_refunded': None,
                    'is_nominal': '0',
                    'is_qty_decimal': '0',
                    'is_virtual': '0',
                    'item_id': '30312',
                    'locked_do_invoice': None,
                    'locked_do_ship': None,
                    'name': u'VO2 Slim Protein Bar 12 unidades - Integralm\xe9dica - Frutas Verm/Choc. Branco',
                    'no_discount': '0',
                    'order_id': '11290',
                    'original_price': '0.0000',
                    'parent_item_id': '30311',
                    'price': '0.0000',
                    'price_incl_tax': None,
                    'product_id': '107',
                    'product_options': 'a:1:{s:15:"info_buyRequest";a:5:{s:4:"uenc";s:184:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9tYXNzYS1lLWVuZXJnaWEvY2F0ZWdvcmlhcy9iYXJyYXMtZGUtcHJvdGVpbmFzL3ZvMi1zbGltLXByb3RlaW4tYmFyLTEyLXVuaWRhZGVzLWludGVncmFsbWVkaWNhLmh0bWw_X19fU0lEPVU,";s:7:"product";s:3:"105";s:15:"related_product";s:0:"";s:15:"super_attribute";a:1:{i:135;s:2:"12";}s:3:"qty";s:1:"1";}}',
                    'product_type': 'simple',
                    'qty_backordered': None,
                    'qty_canceled': '0.0000',
                    'qty_invoiced': '1.0000',
                    'qty_ordered': '1.0000',
                    'qty_refunded': '0.0000',
                    'qty_shipped': '0.0000',
                    'quote_item_id': '96514',
                    'row_invoiced': '0.0000',
                    'row_total': '0.0000',
                    'row_total_incl_tax': None,
                    'row_weight': '0.0000',
                    'sku': '214',
                    'store_id': '1',
                    'tax_amount': '0.0000',
                    'tax_before_discount': None,
                    'tax_canceled': None,
                    'tax_invoiced': '0.0000',
                    'tax_percent': '0.0000',
                    'tax_refunded': None,
                    'updated_at': '2013-06-28 17:08:27',
                    'weee_tax_applied': 'a:0:{}',
                    'weee_tax_applied_amount': '0.0000',
                    'weee_tax_applied_row_amount': '0.0000',
                    'weee_tax_disposition': '0.0000',
                    'weee_tax_row_disposition': '0.0000',
                    'weight': '0.5000'}],
         'order_currency_code': 'BRL',
         'order_id': '11290',
         'original_increment_id': None,
         'payment': {'account_status': None,
                     'additional_data': None,
                     'additional_information': {'CreditCardBrandEnum': 'Mastercard',
                                                'CreditCardTransactionStatusEnum': 'Captured',
                                                'InstallmentCount': '3',
                                                'OrderKey': 'adaa28a7-c809-47d0-88a7-bc26da1bd30b',
                                                'PaymentMethod': 'CreditCard'},
                     'address_status': None,
                     'amount_authorized': None,
                     'amount_canceled': None,
                     'amount_ordered': '203.8900',
                     'amount_paid': '203.8900',
                     'amount_refunded': None,
                     'anet_trans_method': None,
                     'base_amount_authorized': None,
                     'base_amount_canceled': None,
                     'base_amount_ordered': '203.8900',
                     'base_amount_paid': '203.8900',
                     'base_amount_paid_online': '203.8900',
                     'base_amount_refunded': None,
                     'base_amount_refunded_online': None,
                     'base_shipping_amount': '0.0000',
                     'base_shipping_captured': '0.0000',
                     'base_shipping_refunded': None,
                     'cc_approval': None,
                     'cc_avs_status': None,
                     'cc_cid_status': None,
                     'cc_debug_request_body': None,
                     'cc_debug_response_body': None,
                     'cc_debug_response_serialized': None,
                     'cc_exp_month': '5',
                     'cc_exp_year': '16',
                     'cc_last4': '0215',
                     'cc_number_enc': None,
                     'cc_owner': 'Matheus Brusamarello',
                     'cc_secure_verify': None,
                     'cc_ss_issue': None,
                     'cc_ss_start_month': '0',
                     'cc_ss_start_year': '0',
                     'cc_status': None,
                     'cc_status_description': None,
                     'cc_trans_id': None,
                     'cc_type': 'MC',
                     'echeck_account_name': None,
                     'echeck_account_type': None,
                     'echeck_bank_name': None,
                     'echeck_routing_number': None,
                     'echeck_type': None,
                     'last_trans_id': 'fb3a3fe4-3349-40f4-bbfe-b0b4f6787bcd',
                     'method': 'mundipagg_standard',
                     'parent_id': '11290',
                     'paybox_request_number': None,
                     'payment_id': '11290',
                     'po_number': None,
                     'protection_eligibility': None,
                     'quote_payment_id': None,
                     'shipping_amount': '0.0000',
                     'shipping_captured': '0.0000',
                     'shipping_refunded': None},
         'payment_auth_expiration': None,
         'payment_authorization_amount': None,
         'payment_authorization_expiration': None,
         'paypal_ipn_customer_notified': '0',
         'protect_code': 'bc2ad4',
         'quote_address_id': None,
         'quote_id': '39880',
         'relation_child_id': None,
         'relation_child_real_id': None,
         'relation_parent_id': None,
         'relation_parent_real_id': None,
         'remote_ip': '189.73.105.137',
         'shipping_address': {'address_id': '22580',
                              'address_type': 'shipping',
                              'celular': None,
                              'city': u'Xanxer\xea',
                              'company': None,
                              'country_id': 'BR',
                              'cpfcnpj': None,
                              'customer_address_id': None,
                              'customer_id': None,
                              'email': 'bian_ros@hotmail.com',
                              'fax': None,
                              'firstname': 'Matheus',
                              'ie': None,
                              'lastname': 'Brusamarello',
                              'middlename': None,
                              'parent_id': '11290',
                              'postcode': '89820-000',
                              'prefix': None,
                              'quote_address_id': None,
                              'region': 'Santa Catarina',
                              'region_id': '507',
                              'rg': None,
                              'street': u'R. Independ\xeancia\n1034\n402\nLa Salle',
                              'suffix': None,
                              'telephone': '(49)9989-7917',
                              'tipopessoa': None,
                              'vat_id': None,
                              'vat_is_valid': None,
                              'vat_request_date': None,
                              'vat_request_id': None,
                              'vat_request_success': None},
         'shipping_address_id': '22580',
         'shipping_amount': '0.0000',
         'shipping_canceled': None,
         'shipping_description': u'Entrega Normal - Em m\xe9dia 6 dia(s)',
         'shipping_discount_amount': '0.0000',
         'shipping_hidden_tax_amount': '0.0000',
         'shipping_incl_tax': '0.0000',
         'shipping_invoiced': '0.0000',
         'shipping_method': 'pedroteixeira_correios_41111',
         'shipping_refunded': None,
         'shipping_tax_amount': '0.0000',
         'shipping_tax_refunded': None,
         'state': 'processing',
         'status': 'processing',
         'status_history': [{'comment': None,
                             'created_at': '2013-06-28 17:08:27',
                             'entity_name': 'invoice',
                             'is_customer_notified': '1',
                             'is_visible_on_front': '0',
                             'parent_id': '11290',
                             'status': 'processing',
                             'store_id': '1'},
                            {'comment': None,
                             'created_at': '2013-06-28 17:08:27',
                             'entity_name': 'invoice',
                             'is_customer_notified': '1',
                             'is_visible_on_front': '0',
                             'parent_id': '11290',
                             'status': 'pending',
                             'store_id': '1'},
                            {'comment': 'Capturar valor R$203,89 online.',
                             'created_at': '2013-06-28 17:08:27',
                             'entity_name': 'invoice',
                             'is_customer_notified': '2',
                             'is_visible_on_front': '0',
                             'parent_id': '11290',
                             'status': 'processing',
                             'store_id': '1'}],
         'store_currency_code': 'BRL',
         'store_id': '1',
         'store_name': 'Main Website\nMain Website Store\nDefault Store View',
         'store_to_base_rate': '1.0000',
         'store_to_order_rate': '1.0000',
         'subtotal': '203.8900',
         'subtotal_canceled': None,
         'subtotal_incl_tax': '203.8900',
         'subtotal_invoiced': '203.8900',
         'subtotal_refunded': None,
         'tax_amount': '0.0000',
         'tax_canceled': None,
         'tax_invoiced': '0.0000',
         'tax_refunded': None,
         'total_canceled': None,
         'total_due': None,
         'total_invoiced': '203.8900',
         'total_item_count': '4',
         'total_offline_refunded': None,
         'total_online_refunded': None,
         'total_paid': '203.8900',
         'total_qty_ordered': '4.0000',
         'total_refunded': None,
         'updated_at': '2013-06-28 17:08:27',
         'weight': '1.8000',
         'x_forwarded_for': None}

simple_product = {'additional_data': None,
             'affiliateplus_amount': None,
             'affiliateplus_commission': '0.0000',
             'amount_refunded': '0.0000',
             'applied_rule_ids': '1',
             'base_affiliateplus_amount': None,
             'base_amount_refunded': '0.0000',
             'base_cost': None,
             'base_discount_amount': '0.0000',
             'base_discount_invoiced': '0.0000',
             'base_discount_refunded': None,
             'base_hidden_tax_amount': None,
             'base_hidden_tax_invoiced': '0.0000',
             'base_hidden_tax_refunded': None,
             'base_original_price': '0.0000',
             'base_price': '0.0000',
             'base_price_incl_tax': '0.0000',
             'base_row_invoiced': '0.0000',
             'base_row_total': '0.0000',
             'base_row_total_incl_tax': '0.0000',
             'base_tax_amount': '0.0000',
             'base_tax_before_discount': None,
             'base_tax_invoiced': '0.0000',
             'base_tax_refunded': None,
             'base_weee_tax_applied_amount': '0.0000',
             'base_weee_tax_applied_row_amnt': '0.0000',
             'base_weee_tax_applied_row_amount': '0.0000',
             'base_weee_tax_disposition': '0.0000',
             'base_weee_tax_row_disposition': '0.0000',
             'created_at': '2013-06-28 13:32:47',
             'description': None,
             'discount_amount': '0.0000',
             'discount_invoiced': '0.0000',
             'discount_percent': '0.0000',
             'discount_refunded': None,
             'ext_order_item_id': None,
             'free_shipping': '0',
             'gift_message_available': None,
             'gift_message_id': None,
             'hidden_tax_amount': None,
             'hidden_tax_canceled': None,
             'hidden_tax_invoiced': '0.0000',
             'hidden_tax_refunded': None,
             'is_nominal': '0',
             'is_qty_decimal': '0',
             'is_virtual': '0',
             'item_id': '30243',
             'locked_do_invoice': None,
             'locked_do_ship': None,
             'name': u'Luva Protetora para Muscula\xe7\xe3o - CentralFit',
             'no_discount': '0',
             'order_id': '11262',
             'original_price': '0.0000',
             'parent_item_id': None,
             'price': '0.0000',
             'price_incl_tax': '0.0000',
             'product_id': '2108',
             'product_options': u'a:1:{s:15:"info_buyRequest";a:6:{s:4:"uenc";s:108:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9pc28tY2ZtLXplcm8tY2FyYi05MDdnLWludGVncmFsbWVkaWNhLmh0bWw_X19fU0lEPVU,";s:7:"product";s:4:"2108";s:3:"qty";d:1;s:17:"free_catalog_gift";i:1;s:19:"freegift_parent_key";s:32:"e334ea177458f7e0c7e6815079acf967";s:6:"option";s:59:"a:2:{s:5:"label";s:14:"BRINDE GR\xc1TIS";s:5:"value";s:0:"";}";}}',
             'product_type': 'simple',
             'qty_backordered': None,
             'qty_canceled': '0.0000',
             'qty_invoiced': '1.0000',
             'qty_ordered': '1.0000',
             'qty_refunded': '0.0000',
             'qty_shipped': '0.0000',
             'quote_item_id': '96294',
             'row_invoiced': '0.0000',
             'row_total': '0.0000',
             'row_total_incl_tax': '0.0000',
             'row_weight': '0.0000',
             'sku': '3059',
             'store_id': '1',
             'tax_amount': '0.0000',
             'tax_before_discount': None,
             'tax_canceled': None,
             'tax_invoiced': '0.0000',
             'tax_percent': '0.0000',
             'tax_refunded': None,
             'updated_at': '2013-06-28 13:32:53',
             'weee_tax_applied': 'a:0:{}',
             'weee_tax_applied_amount': '0.0000',
             'weee_tax_applied_row_amount': '0.0000',
             'weee_tax_disposition': '0.0000',
             'weee_tax_row_disposition': '0.0000',
             'weight': '0.0500'}

simple_item_in_order = {'additional_data': None,
                         'affiliateplus_amount': None,
                         'affiliateplus_commission': '0.0000',
                         'amount_refunded': '0.0000',
                         'applied_rule_ids': '1',
                         'base_affiliateplus_amount': None,
                         'base_amount_refunded': '0.0000',
                         'base_cost': None,
                         'base_discount_amount': '0.0000',
                         'base_discount_invoiced': '0.0000',
                         'base_discount_refunded': None,
                         'base_hidden_tax_amount': None,
                         'base_hidden_tax_invoiced': '0.0000',
                         'base_hidden_tax_refunded': None,
                         'base_original_price': '0.0000',
                         'base_price': '0.0000',
                         'base_price_incl_tax': '0.0000',
                         'base_row_invoiced': '0.0000',
                         'base_row_total': '0.0000',
                         'base_row_total_incl_tax': '0.0000',
                         'base_tax_amount': '0.0000',
                         'base_tax_before_discount': None,
                         'base_tax_invoiced': '0.0000',
                         'base_tax_refunded': None,
                         'base_weee_tax_applied_amount': '0.0000',
                         'base_weee_tax_applied_row_amnt': '0.0000',
                         'base_weee_tax_applied_row_amount': '0.0000',
                         'base_weee_tax_disposition': '0.0000',
                         'base_weee_tax_row_disposition': '0.0000',
                         'created_at': '2013-06-28 17:08:20',
                         'description': None,
                         'discount_amount': '0.0000',
                         'discount_invoiced': '0.0000',
                         'discount_percent': '0.0000',
                         'discount_refunded': None,
                         'ext_order_item_id': None,
                         'free_shipping': '0',
                         'gift_message_available': None,
                         'gift_message_id': None,
                         'hidden_tax_amount': None,
                         'hidden_tax_canceled': None,
                         'hidden_tax_invoiced': '0.0000',
                         'hidden_tax_refunded': None,
                         'is_nominal': '0',
                         'is_qty_decimal': '0',
                         'is_virtual': '0',
                         'item_id': '30309',
                         'locked_do_invoice': None,
                         'locked_do_ship': None,
                         'name': u'Luva Protetora para Muscula\xe7\xe3o - CentralFit',
                         'no_discount': '0',
                         'order_id': '11290',
                         'original_price': '0.0000',
                         'parent_item_id': None,
                         'price': '0.0000',
                         'price_incl_tax': '0.0000',
                         'product_id': '2108',
                         'product_options': u'a:1:{s:15:"info_buyRequest";a:6:{s:4:"uenc";s:116:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici8xMDAtd2hleS1wcm90ZWluLWdvbGQtc3RhbmRhcmQtMmxicy1vcHRpbXVtLmh0bWw_X19fU0lEPVU,";s:7:"product";s:4:"2108";s:3:"qty";d:1;s:17:"free_catalog_gift";i:1;s:19:"freegift_parent_key";s:32:"269d837afada308dd4aeab28ca2d57e4";s:6:"option";s:59:"a:2:{s:5:"label";s:14:"BRINDE GR\xc1TIS";s:5:"value";s:0:"";}";}}',
                         'product_type': 'simple',
                         'qty_backordered': None,
                         'qty_canceled': '0.0000',
                         'qty_invoiced': '1.0000',
                         'qty_ordered': '1.0000',
                         'qty_refunded': '0.0000',
                         'qty_shipped': '0.0000',
                         'quote_item_id': '96496',
                         'row_invoiced': '0.0000',
                         'row_total': '0.0000',
                         'row_total_incl_tax': '0.0000',
                         'row_weight': '0.0000',
                         'sku': '3059',
                         'store_id': '1',
                         'tax_amount': '0.0000',
                         'tax_before_discount': None,
                         'tax_canceled': None,
                         'tax_invoiced': '0.0000',
                         'tax_percent': '0.0000',
                         'tax_refunded': None,
                         'updated_at': '2013-06-28 17:08:27',
                         'weee_tax_applied': 'a:0:{}',
                         'weee_tax_applied_amount': '0.0000',
                         'weee_tax_applied_row_amount': '0.0000',
                         'weee_tax_disposition': '0.0000',
                         'weee_tax_row_disposition': '0.0000',
                         'weight': '0.0500'
}

item_test_order_01 = {
"original_price":"104.9000",
"product_options":"a:6:{s:15:\"info_buyRequest\";a:5:{s:4:\"uenc\";s:136:\"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9pbXBhY3Qtd2hleS16ZXJvLWNhcmJvLXByb3RlaW4tOTAwZy1uZW9udXRyaS5odG1sP19fX1NJRD1VJm9wdGlvbnM9Y2FydA,,\";s:7:\"product\";s:4:\"1185\";s:15:\"related_product\";s:0:\"\";s:15:\"super_attribute\";a:1:{i:135;s:3:\"105\";}s:3:\"qty\";s:1:\"1\";}s:15:\"attributes_info\";a:1:{i:0;a:2:{s:5:\"label\";s:5:\"Sabor\";s:5:\"value\";s:12:\"Banana Cream\";}}s:11:\"simple_name\";s:63:\"Impact Whey Zero Carbo Protein - 900g - NeoNutri - Banana Cream\";s:10:\"simple_sku\";s:4:\"2169\";s:20:\"product_calculations\";i:1;s:13:\"shipment_type\";i:0;}",
"base_weee_tax_row_disposition":"0.0000",
"sku":"2169",
"cost": "64.3",
"weee_tax_applied_row_amount":"0.0000",
"no_discount":"0",
"weee_tax_applied":"a:0:{}",
"amount_refunded":"0.0000",
"base_discount_amount":"10.0000",
"discount_amount":"10.0000",
"tax_amount":"0.0000",
"name":"Impact Whey Zero Carbo Protein - 900g - NeoNutri",
"qty_canceled":"0.0000",
"discount_percent":"0.0000",
"qty_ordered":"1.0000",
"weight":"1.1000",
"base_row_total":"104.9000",
"qty_invoiced":"0.0000",
"discount_invoiced":"0.0000",
"row_total":"104.9000",
"base_original_price":"104.9000",
"row_invoiced":"0.0000",
"order_id":"11447",
"item_id":"30745",
"weee_tax_applied_amount":"0.0000",
"base_tax_amount":"0.0000",
"applied_rule_ids":"1,8",
"product_id":"1185",
"base_weee_tax_applied_amount":"0.0000",
"qty_refunded":"0.0000",
"affiliateplus_commission":"0.0000",
"base_row_invoiced":"0.0000",
"base_weee_tax_disposition":"0.0000",
"qty_shipped":"0.0000",
"is_qty_decimal":"0",
"quote_item_id":"97763",
"is_virtual":"0",
"base_weee_tax_applied_row_amnt":"0.0000",
"base_weee_tax_applied_row_amount":"0.0000",
"base_price_incl_tax":"104.9000",
"tax_percent":"0.0000",
"tax_invoiced":"0.0000",
"base_tax_invoiced":"0.0000",
"base_price":"104.9000",
"price_incl_tax":"104.9000",
"store_id":"1",
"updated_at":"2013-07-01 01:07:01",
"base_discount_invoiced":"0.0000",
"price":"104.9000",
"free_shipping":"0",
"is_nominal":"0",
"weee_tax_row_disposition":"0.0000",
"product_type":"configurable",
"base_row_total_incl_tax":"104.9000",
"created_at":"2013-07-01 01:07:01",
"row_weight":"0.0000",
"base_amount_refunded":"0.0000",
"row_total_incl_tax":"104.9000",
"weee_tax_disposition":"0.0000"
}

test_order_01 = {'base_shipping_hidden_tax_amount': '0.0000',
                 'base_currency_code': 'BRL',
                 'subtotal_incl_tax': '104.9000',
                 'shipping_method': 'pedroteixeira_correios_41112',
                 'subtotal_canceled': None,
                 'base_discount_refunded': None,
                 'base_shipping_refunded': None,
                 'total_paid': None,
                 'base_adjustment_negative': None,
                 'shipping_refunded': None,
                 'base_hidden_tax_refunded': None,
                 'base_discount_canceled': None,
                 'base_total_invoiced': None,
                 'base_subtotal_canceled': None,
                 'store_to_base_rate': '1.0000',
                 'shipping_tax_amount': '0.0000',
                 'discount_amount': '-10.0000',
                 'adjustment_positive': None,
                 'paypal_ipn_customer_notified': '0',
                 'customer_email': 'testecentralfit1@gmail.com',
                 'edit_increment': None,
                 'base_discount_amount': '-10.0000',
                 'hidden_tax_invoiced': None,
                 'base_hidden_tax_amount': '0.0000',
                 'customer_dob': None,
                 'total_online_refunded': None,
                 'tax_amount': '0.0000',
                 'base_total_due': '141.4100',
                 'base_tax_canceled': None,
                 'email_sent': '1',
                 'total_qty_ordered': '3.0000',
                 'payment_authorization_amount': None,
                 'subtotal_invoiced': None,
                 'protect_code': 'deda28',
                 'original_increment_id': None,
                 'status_history': [{'comment': None, 'status': 'complete', 'is_visible_on_front': '0', 'store_id': '1', 'entity_name': 'order', 'created_at': '2013-07-01 01:12:08', 'is_customer_notified': '0', 'parent_id': '11447'}, {'comment': u'Aguardando pagamento do Boleto Banc\xe1rio', 'status': 'holded', 'is_visible_on_front': '0', 'store_id': '1', 'entity_name': 'order', 'created_at': '2013-07-01 01:07:03', 'is_customer_notified': '0', 'parent_id': '11447'}, {'comment': None, 'status': 'pending', 'is_visible_on_front': '0', 'store_id': '1', 'entity_name': 'order', 'created_at': '2013-07-01 01:07:03', 'is_customer_notified': '1', 'parent_id': '11447'}],
                 'base_total_canceled': None,
                 'total_invoiced': None,
                 'base_shipping_tax_amount': '0.0000',
                 'weight': '1.3000',
                 'base_subtotal': '104.9000',
                 'customer_middlename': None,
                 'total_canceled': None,
                 'relation_parent_id': None,
                 'base_subtotal_invoiced': None,
                 'discount_invoiced': None,
                 'base_shipping_hidden_tax_amnt': '0.0000',
                 'base_shipping_invoiced': None,
                 'customer_group_id': '1',
                 'shipping_tax_refunded': None,
                 'total_item_count': '3',
                 'shipping_amount': '46.5100',
                 'customer_gender': None,
                 'state': 'holded',
                 'shipping_discount_amount': '0.0000',
                 'customer_lastname': 'Mansano',
                 'base_subtotal_incl_tax': '104.9000',
                 'customer_id': '14286',
                 'shipping_description': u'Entrega R\xe1pida - Em m\xe9dia 4 dia(s)',
                 'base_shipping_amount': '46.5100',
                 'order_id': '11447',
                 'can_ship_partially_item': None,
                 'relation_child_real_id': None,
                 'base_to_global_rate': '1.0000',
                 'base_total_paid': None,
                 'base_tax_amount': '0.0000',
                 'applied_rule_ids': '1,8',
                 'base_hidden_tax_invoiced': None,
                 'items': [
                     {'original_price': '104.9000', 'product_options': 'a:6:{s:15:"info_buyRequest";a:5:{s:4:"uenc";s:136:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9pbXBhY3Qtd2hleS16ZXJvLWNhcmJvLXByb3RlaW4tOTAwZy1uZW9udXRyaS5odG1sP19fX1NJRD1VJm9wdGlvbnM9Y2FydA,,";s:7:"product";s:4:"1185";s:15:"related_product";s:0:"";s:15:"super_attribute";a:1:{i:135;s:3:"105";}s:3:"qty";s:1:"1";}s:15:"attributes_info";a:1:{i:0;a:2:{s:5:"label";s:5:"Sabor";s:5:"value";s:12:"Banana Cream";}}s:11:"simple_name";s:63:"Impact Whey Zero Carbo Protein - 900g - NeoNutri - Banana Cream";s:10:"simple_sku";s:4:"2169";s:20:"product_calculations";i:1;s:13:"shipment_type";i:0;}', 'hidden_tax_refunded': None, 'base_discount_refunded': None, 'base_weee_tax_row_disposition': '0.0000', 'base_hidden_tax_refunded': None, 'sku': '2169', 'weee_tax_applied_row_amount': '0.0000', 'no_discount': '0', 'weee_tax_applied': 'a:0:{}', 'amount_refunded': '0.0000', 'qty_backordered': None, 'has_children': True, 'base_discount_amount': '10.0000', 'hidden_tax_invoiced': None, 'discount_amount': '10.0000', 'tax_amount': '0.0000', 'name': 'Impact Whey Zero Carbo Protein - 900g - NeoNutri', 'locked_do_invoice': None, 'qty_canceled': '0.0000', 'discount_percent': '0.0000', 'qty_ordered': '1.0000', 'weight': '1.1000', 'base_row_total': '104.9000', 'qty_invoiced': '0.0000', 'discount_invoiced': '0.0000', 'row_total': '104.9000', 'base_original_price': '104.9000', 'ext_order_item_id': None, 'base_hidden_tax_amount': None, 'row_invoiced': '0.0000', 'parent_item_id': None, 'order_id': '11447', 'hidden_tax_canceled': None, 'item_id': '30745', 'weee_tax_applied_amount': '0.0000', 'base_tax_amount': '0.0000', 'applied_rule_ids': '1,8', 'product_id': '1185', 'base_hidden_tax_invoiced': None, 'base_weee_tax_applied_amount': '0.0000', 'affiliateplus_amount': None, 'qty_refunded': '0.0000', 'affiliateplus_commission': '0.0000', 'base_row_invoiced': '0.0000', 'hidden_tax_amount': None, 'locked_do_ship': None, 'base_weee_tax_disposition': '0.0000', 'qty_shipped': '0.0000', 'is_qty_decimal': '0', 'quote_item_id': '97763', 'is_virtual': '0', 'base_tax_refunded': None, 'gift_message_id': None, 'gift_message_available': None, 'tax_refunded': None, 'base_weee_tax_applied_row_amnt': '0.0000', 'base_weee_tax_applied_row_amount': '0.0000', 'tax_canceled': None, 'tax_before_discount': None, 'base_price_incl_tax': '104.9000', 'tax_percent': '0.0000', 'tax_invoiced': '0.0000', 'base_tax_invoiced': '0.0000', 'additional_data': None, 'base_price': '104.9000', 'price_incl_tax': '104.9000', 'base_affiliateplus_amount': None, 'store_id': '1', 'updated_at': '2013-07-01 01:07:01', 'base_discount_invoiced': '0.0000', 'base_cost': None, 'base_tax_before_discount': None, 'description': None, 'price': '104.9000', 'discount_refunded': None, 'free_shipping': '0', 'is_nominal': '0', 'weee_tax_row_disposition': '0.0000', 'product_type': 'configurable', 'base_row_total_incl_tax': '104.9000', 'created_at': '2013-07-01 01:07:01', 'row_weight': '0.0000', 'base_amount_refunded': '0.0000', 'row_total_incl_tax': '104.9000', 'weee_tax_disposition': '0.0000'},
                     {'original_price': '0.0000', 'price_incl_tax': None, 'base_row_invoiced': '0.0000', 'hidden_tax_amount': None, 'store_id': '1', 'weight': '1.1000', 'row_total': '0.0000', 'base_weee_tax_disposition': '0.0000', 'base_row_total': '0.0000', 'qty_invoiced': '0.0000', 'updated_at': '2013-07-01 01:07:01', 'discount_invoiced': '0.0000', 'qty_shipped': '0.0000', 'base_discount_refunded': None, 'tax_refunded': None, 'base_weee_tax_row_disposition': '0.0000', 'locked_do_ship': None, 'base_cost': None, 'weee_tax_applied_amount': '0.0000', 'base_hidden_tax_refunded': None, 'is_qty_decimal': '0', 'sku': '2169', 'weee_tax_applied_row_amount': '0.0000', 'free_shipping': '0', 'base_tax_amount': '0.0000', 'base_original_price': None, 'tax_invoiced': '0.0000', 'weee_tax_row_disposition': '0.0000', 'base_tax_before_discount': None, 'is_virtual': '0', 'ext_order_item_id': None, 'base_tax_refunded': None, 'gift_message_id': None, 'gift_message_available': None, 'base_hidden_tax_amount': None, 'weee_tax_applied': 'a:0:{}', 'discount_amount': '0.0000', 'product_options': 'a:1:{s:15:"info_buyRequest";a:7:{s:4:"uenc";s:136:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9pbXBhY3Qtd2hleS16ZXJvLWNhcmJvLXByb3RlaW4tOTAwZy1uZW9udXRyaS5odG1sP19fX1NJRD1VJm9wdGlvbnM9Y2FydA,,";s:7:"product";s:4:"1185";s:15:"related_product";s:0:"";s:15:"super_attribute";a:1:{i:135;s:3:"105";}s:3:"qty";s:1:"1";s:12:"freegift_key";s:32:"404dcc91b2aeaa7caa47487d1483e48a";s:13:"apllied_rules";s:32:"a:2:{i:0;s:2:"12";i:1;s:2:"29";}";}}', 'base_weee_tax_applied_row_amnt': None, 'amount_refunded': '0.0000', 'qty_backordered': None, 'base_row_total_incl_tax': None, 'parent_item_id': '30745', 'description': None, 'order_id': '11447', 'price': '0.0000', 'discount_refunded': None, 'no_discount': '0', 'base_discount_amount': '0.0000', 'hidden_tax_canceled': None, 'base_weee_tax_applied_row_amount': None, 'tax_canceled': None, 'hidden_tax_invoiced': None, 'item_id': '30746', 'tax_amount': '0.0000', 'is_nominal': '0', 'quote_item_id': '97764', 'tax_before_discount': None, 'base_price_incl_tax': None, 'tax_percent': '0.0000', 'product_id': '1186', 'applied_rule_ids': '1', 'product_type': 'simple', 'name': 'Impact Whey Zero Carbo Protein - 900g - NeoNutri - Banana Cream', 'base_tax_invoiced': '0.0000', 'locked_do_invoice': None, 'base_hidden_tax_invoiced': None, 'row_invoiced': '0.0000', 'created_at': '2013-07-01 01:07:01', 'base_affiliateplus_amount': None, 'row_weight': '0.0000', 'qty_ordered': '1.0000', 'row_total_incl_tax': None, 'base_weee_tax_applied_amount': '0.0000', 'base_discount_invoiced': '0.0000', 'affiliateplus_amount': None, 'qty_canceled': '0.0000', 'discount_percent': '0.0000', 'base_amount_refunded': '0.0000', 'qty_refunded': '0.0000', 'affiliateplus_commission': '0.0000', 'weee_tax_disposition': '0.0000', 'additional_data': None, 'hidden_tax_refunded': None, 'base_price': '0.0000'},
                     {'original_price': '0.0000', 'price_incl_tax': '0.0000', 'base_row_invoiced': '0.0000', 'hidden_tax_amount': None, 'store_id': '1', 'weight': '0.0500', 'row_total': '0.0000', 'base_weee_tax_disposition': '0.0000', 'base_row_total': '0.0000', 'qty_invoiced': '0.0000', 'updated_at': '2013-07-01 01:07:01', 'discount_invoiced': '0.0000', 'qty_shipped': '0.0000', 'base_discount_refunded': None, 'tax_refunded': None, 'base_weee_tax_row_disposition': '0.0000', 'locked_do_ship': None, 'base_cost': None, 'weee_tax_applied_amount': '0.0000', 'base_hidden_tax_refunded': None, 'is_qty_decimal': '0', 'sku': '3059', 'weee_tax_applied_row_amount': '0.0000', 'free_shipping': '0', 'base_tax_amount': '0.0000', 'base_original_price': '0.0000', 'tax_invoiced': '0.0000', 'weee_tax_row_disposition': '0.0000', 'base_tax_before_discount': None, 'is_virtual': '0', 'ext_order_item_id': None, 'base_tax_refunded': None, 'gift_message_id': None, 'gift_message_available': None, 'base_hidden_tax_amount': None, 'weee_tax_applied': 'a:0:{}', 'discount_amount': '0.0000', 'product_options': u'a:1:{s:15:"info_buyRequest";a:6:{s:4:"uenc";s:136:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9pbXBhY3Qtd2hleS16ZXJvLWNhcmJvLXByb3RlaW4tOTAwZy1uZW9udXRyaS5odG1sP19fX1NJRD1VJm9wdGlvbnM9Y2FydA,,";s:7:"product";s:4:"2108";s:3:"qty";d:1;s:17:"free_catalog_gift";i:1;s:19:"freegift_parent_key";s:32:"404dcc91b2aeaa7caa47487d1483e48a";s:6:"option";s:59:"a:2:{s:5:"label";s:14:"BRINDE GR\xc1TIS";s:5:"value";s:0:"";}";}}', 'base_weee_tax_applied_row_amnt': '0.0000', 'amount_refunded': '0.0000', 'qty_backordered': None, 'base_row_total_incl_tax': '0.0000', 'parent_item_id': None, 'description': None, 'order_id': '11447', 'price': '0.0000', 'discount_refunded': None, 'no_discount': '0', 'base_discount_amount': '0.0000', 'hidden_tax_canceled': None, 'base_weee_tax_applied_row_amount': '0.0000', 'tax_canceled': None, 'hidden_tax_invoiced': None, 'item_id': '30747', 'tax_amount': '0.0000', 'is_nominal': '0', 'quote_item_id': '97765', 'tax_before_discount': None, 'base_price_incl_tax': '0.0000', 'tax_percent': '0.0000', 'product_id': '2108', 'applied_rule_ids': '1,8', 'product_type': 'simple', 'name': u'Luva Protetora para Muscula\xe7\xe3o - CentralFit', 'base_tax_invoiced': '0.0000', 'locked_do_invoice': None, 'base_hidden_tax_invoiced': None, 'row_invoiced': '0.0000', 'created_at': '2013-07-01 01:07:01', 'base_affiliateplus_amount': None, 'row_weight': '0.0000', 'qty_ordered': '1.0000', 'row_total_incl_tax': '0.0000', 'base_weee_tax_applied_amount': '0.0000', 'base_discount_invoiced': '0.0000', 'affiliateplus_amount': None, 'qty_canceled': '0.0000', 'discount_percent': '0.0000', 'base_amount_refunded': '0.0000', 'qty_refunded': '0.0000', 'affiliateplus_commission': '0.0000', 'weee_tax_disposition': '0.0000', 'additional_data': None, 'hidden_tax_refunded': None, 'base_price': '0.0000'},
                     {'original_price': '0.0000', 'price_incl_tax': '0.0000', 'base_row_invoiced': '0.0000', 'hidden_tax_amount': None, 'store_id': '1', 'weight': '0.1500', 'row_total': '0.0000', 'base_weee_tax_disposition': '0.0000', 'base_row_total': '0.0000', 'qty_invoiced': '0.0000', 'updated_at': '2013-07-01 01:07:01', 'discount_invoiced': '0.0000', 'qty_shipped': '0.0000', 'base_discount_refunded': None, 'tax_refunded': None, 'base_weee_tax_row_disposition': '0.0000', 'locked_do_ship': None, 'base_cost': None, 'weee_tax_applied_amount': '0.0000', 'base_hidden_tax_refunded': None, 'is_qty_decimal': '0', 'sku': '2326', 'weee_tax_applied_row_amount': '0.0000', 'free_shipping': '0', 'base_tax_amount': '0.0000', 'base_original_price': '0.0000', 'tax_invoiced': '0.0000', 'weee_tax_row_disposition': '0.0000', 'base_tax_before_discount': None, 'is_virtual': '0', 'ext_order_item_id': None, 'base_tax_refunded': None, 'gift_message_id': None, 'gift_message_available': None, 'base_hidden_tax_amount': None, 'weee_tax_applied': 'a:0:{}', 'discount_amount': '0.0000', 'product_options': u'a:1:{s:15:"info_buyRequest";a:6:{s:4:"uenc";s:136:"aHR0cDovL3d3dy5jZW50cmFsZml0LmNvbS5ici9pbXBhY3Qtd2hleS16ZXJvLWNhcmJvLXByb3RlaW4tOTAwZy1uZW9udXRyaS5odG1sP19fX1NJRD1VJm9wdGlvbnM9Y2FydA,,";s:7:"product";s:4:"1345";s:3:"qty";d:1;s:17:"free_catalog_gift";i:1;s:19:"freegift_parent_key";s:32:"404dcc91b2aeaa7caa47487d1483e48a";s:6:"option";s:59:"a:2:{s:5:"label";s:14:"BRINDE GR\xc1TIS";s:5:"value";s:0:"";}";}}', 'base_weee_tax_applied_row_amnt': '0.0000', 'amount_refunded': '0.0000', 'qty_backordered': None, 'base_row_total_incl_tax': '0.0000', 'parent_item_id': None, 'description': None, 'order_id': '11447', 'price': '0.0000', 'discount_refunded': None, 'no_discount': '0', 'base_discount_amount': '0.0000', 'hidden_tax_canceled': None, 'base_weee_tax_applied_row_amount': '0.0000', 'tax_canceled': None, 'hidden_tax_invoiced': None, 'item_id': '30748', 'tax_amount': '0.0000', 'is_nominal': '0', 'quote_item_id': '97766', 'tax_before_discount': None, 'base_price_incl_tax': '0.0000', 'tax_percent': '0.0000', 'product_id': '1345', 'applied_rule_ids': '1,8', 'product_type': 'simple', 'name': 'Coqueteleira Shaker - 700ml - NeoNutri', 'base_tax_invoiced': '0.0000', 'locked_do_invoice': None, 'base_hidden_tax_invoiced': None, 'row_invoiced': '0.0000', 'created_at': '2013-07-01 01:07:01', 'base_affiliateplus_amount': None, 'row_weight': '0.0000', 'qty_ordered': '1.0000', 'row_total_incl_tax': '0.0000', 'base_weee_tax_applied_amount': '0.0000', 'base_discount_invoiced': '0.0000', 'affiliateplus_amount': None, 'qty_canceled': '0.0000', 'discount_percent': '0.0000', 'base_amount_refunded': '0.0000', 'qty_refunded': '0.0000', 'affiliateplus_commission': '0.0000', 'weee_tax_disposition': '0.0000', 'additional_data': None, 'hidden_tax_refunded': None, 'base_price': '0.0000'}],
                 'customer_is_guest': '0', 'forced_do_shipment_with_invoice': None, 'base_total_online_refunded': None, 'billing_address': {'address_id': '22893', 'region_id': '485', 'vat_request_id': None, 'telephone': '(11)99318-8135', 'tipopessoa': None, 'vat_id': None, 'prefix': None, 'street': u'Rua Rio Grande do Sul\n343\napto 1101\nPrevent\xf3rio', 'postcode': '69900-150', 'ie': None, 'suffix': None, 'city': 'Rio Branco', 'country_id': 'BR', 'parent_id': '11447', 'rg': None, 'address_type': 'billing', 'email': 'testecentralfit1@gmail.com', 'quote_address_id': None, 'customer_address_id': '16037', 'fax': None, 'firstname': 'Felipe', 'middlename': None, 'lastname': 'Mansano', 'company': None, 'vat_is_valid': None, 'cpfcnpj': None, 'customer_id': None, 'vat_request_success': None, 'region': 'Acre', 'vat_request_date': None, 'celular': None},
                 'hidden_tax_refunded': None, 'discount_canceled': None, 'customer_note_notify': '1', 'base_total_offline_refunded': None, 'customer_firstname': 'Felipe', 'hold_before_status': None, 'base_total_refunded': None, 'customer_taxvat': '411.921.511-35', 'shipping_hidden_tax_amount': '0.0000', 'quote_id': '40394', 'store_name': 'Main Website\nMain Website Store\nDefault Store View', 'base_affiliateplus_discount': None, 'customer_suffix': None, 'is_virtual': '0', 'base_tax_refunded': None, 'relation_parent_real_id': None, 'adjustment_negative': None, 'base_shipping_canceled': None, 'base_subtotal_refunded': None, 'total_refunded': None, 'tax_refunded': None, 'quote_address_id': None, 'shipping_invoiced': None, 'order_currency_code': 'BRL', 'hidden_tax_amount': '0.0000', 'tax_canceled': None, 'base_total_invoiced_cost': None, 'coupon_rule_name': 'Cupom Vip 10', 'grand_total': '141.4100', 'base_shipping_incl_tax': '46.5100', 'hold_before_state': None, 'tax_invoiced': None, 'base_tax_invoiced': None, 'relation_child_id': None, 'total_due': '141.4100', 'shipping_address_id': '22894',
                 'shipping_address': {'address_id': '22894', 'region_id': '485', 'vat_request_id': None, 'telephone': '(11)99318-8135', 'tipopessoa': None, 'vat_id': None, 'prefix': None, 'street': u'Rua Rio Grande do Sul\n343\napto 1101\nPrevent\xf3rio', 'postcode': '69900-150', 'ie': None, 'suffix': None, 'city': 'Rio Branco', 'country_id': 'BR', 'parent_id': '11447', 'rg': None, 'address_type': 'shipping', 'email': 'testecentralfit1@gmail.com', 'quote_address_id': None, 'customer_address_id': None, 'fax': None, 'firstname': 'Felipe', 'middlename': None, 'lastname': 'Mansano', 'company': None, 'vat_is_valid': None, 'cpfcnpj': None, 'customer_id': None, 'vat_request_success': None, 'region': 'Acre', 'vat_request_date': None, 'celular': None}, 'ext_order_id': None, 'shipping_canceled': None, 'payment_authorization_expiration': None, 'total_offline_refunded': None, 'store_id': '1', 'updated_at': '2013-07-01 01:12:08', 'base_discount_invoiced': None, 'global_currency_code': 'BRL', 'x_forwarded_for': None, 'base_total_qty_ordered': None, 'base_shipping_tax_refunded': None, 'base_shipping_discount_amount': '0.0000', 'increment_id': '100011451', 'store_currency_code': 'BRL', 'forced_shipment_with_invoice': None, 'shipping_incl_tax': '46.5100', 'gift_message_id': None, 'base_grand_total': '141.4100', 'payment_auth_expiration': None, 'billing_address_id': '22893', 'remote_ip': '179.208.128.105', 'status': 'complete', 'customer_note': None, 'discount_description': 'CupomVIP10', 'discount_refunded': None, 'base_to_order_rate': '1.0000', 'subtotal': '104.9000',
                 'payment': {'cc_ss_issue': None, 'protection_eligibility': None, 'base_amount_paid_online': None, 'cc_cid_status': None, 'cc_exp_year': None, 'echeck_account_type': None, 'additional_information': {'PaymentMethod': 'BoletoBancario', 'OrderKey': '1a6b8adc-b2ae-4471-bd64-a2b5f1d5b302', 'BoletoUrl': 'https://transaction.mundipaggone.com/Boleto/ViewBoleto.aspx?bc10880a-921a-4db7-a74e-7ab598360b0b'}, 'cc_debug_response_serialized': None, 'base_amount_authorized': None, 'base_amount_ordered': '141.4100', 'cc_debug_response_body': None, 'base_shipping_refunded': None, 'shipping_captured': None, 'shipping_refunded': None, 'cc_ss_start_year': '0', 'cc_ss_start_month': '0', 'base_shipping_captured': None, 'echeck_account_name': None, 'cc_debug_request_body': None, 'shipping_amount': '46.5100', 'amount_ordered': '141.4100', 'quote_payment_id': None, 'cc_approval': None, 'parent_id': '11447', 'echeck_routing_number': None, 'base_amount_paid': None, 'method': 'mundipagg_standard', 'echeck_type': None, 'amount_refunded': None, 'base_shipping_amount': '46.5100', 'amount_paid': None, 'cc_type': None, 'cc_last4': None, 'last_trans_id': 'bc10880a-921a-4db7-a74e-7ab598360b0b', 'cc_trans_id': None, 'amount_authorized': None, 'base_amount_canceled': None, 'cc_status': None, 'payment_id': '11447', 'anet_trans_method': None, 'address_status': None, 'cc_status_description': None, 'echeck_bank_name': None, 'base_amount_refunded_online': None, 'po_number': None, 'amount_canceled': None, 'account_status': None, 'cc_exp_month': None, 'cc_number_enc': None, 'base_amount_refunded': None, 'cc_avs_status': None, 'cc_owner': None, 'paybox_request_number': None, 'additional_data': None, 'cc_secure_verify': None}, 'store_to_order_rate': '1.0000', 'ext_customer_id': None, 'created_at': '2013-07-01 01:07:01', 'coupon_code': 'CupomVIP10', 'can_ship_partially': None, 'affiliateplus_discount': None, 'base_adjustment_positive': None, 'customer_prefix': None, 'subtotal_refunded': None}